sudo: false

language: go
go:
- 1.5.3
- tip

env:
- GO15VENDOREXPERIMENT=1

install:
- go get golang.org/x/tools/cmd/vet

script:
- "! gofmt -l $(find . -path ./vendor -prune -o -name '*.go' -print) | read nothing"
- go vet
- go test -v $(go list ./... | grep -v /vendor/)
- go build
- ./end-to-end-test.sh
